//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.17 at 11:43:43 PM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://my.simplews.ru", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.simplews.my;
